name: Release Deliver Docs

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Used Python version'
        required: false
        default: "3.8"
        type: string
      scenario-name:
        description: 'Name from the Tox szenario for generate the docs'
        required: false
        default: "docs"
        type: string
      generated-docs-folder:
        description: 'Folder with with generated docs'
        required: false
        default: ".tox/docs/tmp/html"
        type: string
    secrets:
      token:
        required: true

jobs:
  publish_docs:
    name: "Publish the HTML Documentation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        run: tox -e ${{ inputs.scenario-name }}

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ${{ inputs.generated-docs-folder }}
          token: ${{ secrets.token }}
